groups:
  - name: test_alert
    rules:
      - alert: TestAlert
        expr: vector(1)
        for: 20s
        labels:
          severity: critical
        annotations:
          summary: "Test Alert"
          description: "This is a test alert to verify email notifications."
  - name: cpu_alerts
  rules:
  - alert: HighCPUUsage
    expr: 100 - (avg(irate(node_cpu_seconds_total{mode="idle"}[5m])) by (instance) * 100) > 10
    for: 20s
    labels:
      severity: critical
    annotations:
      summary: "High CPU usage detected on {{ $labels.instance }}"
      description: "CPU usage has been above 10% for the last 20 seconds."
